language: java

env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring52-next

cache:
  directories:
    - $HOME/.m2

install: true

script: "./mvnw clean dependency:list test -Pjava11,${PROFILE} -Dsort -U"
